const peoples = [
    { id: 1, name: "Alice Johnson", city: "New York" },
    { id: 2, name: "Bob Smith", city: "Los Angeles" },
    { id: 3, name: "Cathy Brown", city: "Chicago" },
    { id: 4, name: "David Wilson", city: "Houston" },
    { id: 5, name: "Eva Harris", city: "Phoenix" },
    { id: 6, name: "Frank Lewis", city: "Philadelphia" },
    { id: 7, name: "Grace Walker", city: "San Antonio" },
    { id: 8, name: "Henry Hall", city: "San Diego" },
    { id: 9, name: "Ivy Young", city: "Dallas" },
    { id: 10, name: "Jack King", city: "San Jose" },
    { id: 11, name: "Kathy Wright", city: "Austin" },
    { id: 12, name: "Leo Scott", city: "Jacksonville" },
    { id: 13, name: "Mia Turner", city: "Fort Worth" },
    { id: 14, name: "Nate Adams", city: "Columbus" },
    { id: 15, name: "Olivia Thomas", city: "San Francisco" },
    { id: 16, name: "Paul Martinez", city: "Charlotte" },
    { id: 17, name: "Quinn Garcia", city: "Indianapolis" },
    { id: 18, name: "Rose Hernandez", city: "Seattle" },
    { id: 19, name: "Sam Robinson", city: "Denver" },
    { id: 20, name: "Tina Clark", city: "Washington" },
    { id: 21, name: "Uma Rodriguez", city: "Boston" },
    { id: 22, name: "Victor Lee", city: "El Paso" },
    { id: 23, name: "Wendy Perez", city: "Detroit" },
    { id: 24, name: "Xander White", city: "Nashville" },
    { id: 25, name: "Yara Carter", city: "Memphis" },
    { id: 26, name: "Zane Green", city: "Portland" },
    { id: 27, name: "Amy Brooks", city: "Oklahoma City" },
    { id: 28, name: "Ben Bailey", city: "Las Vegas" },
    { id: 29, name: "Cara James", city: "Louisville" },
    { id: 30, name: "Dan Russell", city: "Baltimore" },
    { id: 31, name: "Ella Griffin", city: "Milwaukee" },
    { id: 32, name: "Finn Diaz", city: "Albuquerque" },
    { id: 33, name: "Gina Simmons", city: "Tucson" },
    { id: 34, name: "Hank Foster", city: "Fresno" },
    { id: 35, name: "Isla Bryant", city: "Sacramento" },
    { id: 36, name: "Jake Alexander", city: "Kansas City" },
    { id: 37, name: "Lara Hayes", city: "Long Beach" },
    { id: 38, name: "Mark Myers", city: "Mesa" },
    { id: 39, name: "Nina Chen", city: "Atlanta" },
    { id: 40, name: "Oscar Sanders", city: "Colorado Springs" },
    { id: 41, name: "Pia Morris", city: "Virginia Beach" },
    { id: 42, name: "Ronnie Reed", city: "Raleigh" },
    { id: 43, name: "Sara Price", city: "Omaha" },
    { id: 44, name: "Tom Hunter", city: "Miami" },
    { id: 45, name: "Una Bell", city: "Oakland" },
    { id: 46, name: "Vince Rogers", city: "Minneapolis" },
    { id: 47, name: "Willa Murphy", city: "Tulsa" },
    { id: 48, name: "Xena Cooper", city: "Wichita" },
    { id: 49, name: "Yusuf Peterson", city: "Arlington" },
    { id: 50, name: "Zoe Hughes", city: "New Orleans" }
];

export default peoples
